json.id task.id
json.title task.title
json.start_time task.start_time
json.end_time task.end_time
json.description task.description
json.priority task.priority
json.required_time task.required_time
json.reminder task.reminder
json.created_at task.created_at
json.updated_at task.updated_at
