default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: time_management_app_development

test:
  <<: *default
  database: time_management_app_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  username: <%= ENV['PGUSER'] || 'postgres' %>
  password: <%= ENV['PGPASSWORD'] %>
  host: <%= ENV['PGHOST'] %>
  port: <%= ENV['PGPORT'] || 5432 %>
  database: <%= ENV['PGDATABASE'] %>
  sslmode: <%= ENV['PGSSLMODE'] || 'require' %>
